COUNTRY_PHONE_CC = [
  ("US", "1", "USA"),
  ("GB", "44", "UK"),
  ("DZ", "213", "Algeria"),
  ("AD", "376", "Andorra"),
  ("AO", "244", "Angola"),
  ("AI", "1264", "Anguilla"),
  ("AG", "1268", "Antigua & Barbuda"),
  ("AR", "54", "Argentina"),
  ("AM", "374", "Armenia"),
  ("AW", "297", "Aruba"),
  ("AU", "61", "Australia"),
  ("AT", "43", "Austria"),
  ("AZ", "994", "Azerbaijan"),
  ("BS", "1242", "Bahamas"),
  ("BH", "973", "Bahrain"),
  ("BD", "880", "Bangladesh"),
  ("BB", "1246", "Barbados"),
  ("BY", "375", "Belarus"),
  ("BE", "32", "Belgium"),
  ("BZ", "501", "Belize"),
  ("BJ", "229", "Benin"),
  ("BM", "1441", "Bermuda"),
  ("BT", "975", "Bhutan"),
  ("BO", "591", "Bolivia"),
  ("BA", "387", "Bosnia Herzegovina"),
  ("BW", "267", "Botswana"),
  ("BR", "55", "Brazil"),
  ("BN", "673", "Brunei"),
  ("BG", "359", "Bulgaria"),
  ("BF", "226", "Burkina Faso"),
  ("BI", "257", "Burundi"),
  ("KH", "855", "Cambodia"),
  ("CM", "237", "Cameroon"),
  ("CA", "1", "Canada"),
  ("CV", "238", "Cape Verde Islands"),
  ("KY", "1345", "Cayman Islands"),
  ("CF", "236", "Central African Republic"),
  ("CL", "56", "Chile"),
  ("CN", "86", "China"),
  ("CO", "57", "Colombia"),
  ("KM", "269", "Comoros"),
  ("CG", "242", "Congo"),
  ("CK", "682", "Cook Islands"),
  ("CR", "506", "Costa Rica"),
  ("HR", "385", "Croatia"),
  ("CU", "53", "Cuba"),
  ("CY", "90", "Cyprus - North"),
  ("CY", "357", "Cyprus - South"),
  ("CZ", "420", "Czech Republic"),
  ("DK", "45", "Denmark"),
  ("DJ", "253", "Djibouti"),
  ("DM", "1809", "Dominica"),
  ("DO", "1809", "Dominican Republic"),
  ("EC", "593", "Ecuador"),
  ("EG", "20", "Egypt"),
  ("SV", "503", "El Salvador"),
  ("GQ", "240", "Equatorial Guinea"),
  ("ER", "291", "Eritrea"),
  ("EE", "372", "Estonia"),
  ("ET", "251", "Ethiopia"),
  ("FK", "500", "Falkland Islands"),
  ("FO", "298", "Faroe Islands"),
  ("FJ", "679", "Fiji"),
  ("FI", "358", "Finland"),
  ("FR", "33", "France"),
  ("GF", "594", "French Guiana"),
  ("PF", "689", "French Polynesia"),
  ("GA", "241", "Gabon"),
  ("GM", "220", "Gambia"),
  ("GE", "7880", "Georgia"),
  ("DE", "49", "Germany"),
  ("GH", "233", "Ghana"),
  ("GI", "350", "Gibraltar"),
  ("GR", "30", "Greece"),
  ("GL", "299", "Greenland"),
  ("GD", "1473", "Grenada"),
  ("GP", "590", "Guadeloupe"),
  ("GU", "671", "Guam"),
  ("GT", "502", "Guatemala"),
  ("GN", "224", "Guinea"),
  ("GW", "245", "Guinea - Bissau"),
  ("GY", "592", "Guyana"),
  ("HT", "509", "Haiti"),
  ("HN", "504", "Honduras"),
  ("HK", "852", "Hong Kong"),
  ("HU", "36", "Hungary"),
  ("IS", "354", "Iceland"),
  ("IN", "91", "India"),
  ("ID", "62", "Indonesia"),
  ("IQ", "964", "Iraq"),
  ("IR", "98", "Iran"),
  ("IE", "353", "Ireland"),
  ("IL", "972", "Israel"),
  ("IT", "39", "Italy"),
  ("JM", "1876", "Jamaica"),
  ("JP", "81", "Japan"),
  ("JO", "962", "Jordan"),
  ("KZ", "7", "Kazakhstan"),
  ("KE", "254", "Kenya"),
  ("KI", "686", "Kiribati"),
  ("KR", "82", "Korea - South"),
  ("KW", "965", "Kuwait"),
  ("KG", "996", "Kyrgyzstan"),
  ("LA", "856", "Laos"),
  ("LV", "371", "Latvia"),
  ("LB", "961", "Lebanon"),
  ("LS", "266", "Lesotho"),
  ("LR", "231", "Liberia"),
  ("LY", "218", "Libya"),
  ("LI", "417", "Liechtenstein"),
  ("LT", "370", "Lithuania"),
  ("LU", "352", "Luxembourg"),
  ("MO", "853", "Macao"),
  ("MK", "389", "Macedonia"),
  ("MG", "261", "Madagascar"),
  ("MW", "265", "Malawi"),
  ("MY", "60", "Malaysia"),
  ("MV", "960", "Maldives"),
  ("ML", "223", "Mali"),
  ("MT", "356", "Malta"),
  ("MH", "692", "Marshall Islands"),
  ("MQ", "596", "Martinique"),
  ("MR", "222", "Mauritania"),
  ("YT", "269", "Mayotte"),
  ("MX", "52", "Mexico"),
  ("FM", "691", "Micronesia"),
  ("MD", "373", "Moldova"),
  ("MC", "377", "Monaco"),
  ("MN", "976", "Mongolia"),
  ("MS", "1664", "Montserrat"),
  ("MA", "212", "Morocco"),
  ("MZ", "258", "Mozambique"),
  ("MN", "95", "Myanmar"),
  ("NA", "264", "Namibia"),
  ("NR", "674", "Nauru"),
  ("NP", "977", "Nepal"),
  ("NL", "31", "Netherlands"),
  ("NC", "687", "New Caledonia"),
  ("NZ", "64", "New Zealand"),
  ("NI", "505", "Nicaragua"),
  ("NE", "227", "Niger"),
  ("NG", "234", "Nigeria"),
  ("NU", "683", "Niue"),
  ("NF", "672", "Norfolk Islands"),
  ("NP", "670", "Northern Marianas"),
  ("NO", "47", "Norway"),
  ("OM", "968", "Oman"),
  ("PK", "92", "Pakistan"),
  ("PW", "680", "Palau"),
  ("PA", "507", "Panama"),
  ("PG", "675", "Papua New Guinea"),
  ("PY", "595", "Paraguay"),
  ("PE", "51", "Peru"),
  ("PH", "63", "Philippines"),
  ("PL", "48", "Poland"),
  ("PT", "351", "Portugal"),
  ("PR", "1787", "Puerto Rico"),
  ("QA", "974", "Qatar"),
  ("RE", "262", "Reunion"),
  ("RO", "40", "Romania"),
  ("RU", "7", "Russia"),
  ("RW", "250", "Rwanda"),
  ("SM", "378", "San Marino"),
  ("ST", "239", "Sao Tome & Principe"),
  ("SA", "966", "Saudi Arabia"),
  ("SN", "221", "Senegal"),
  ("CS", "381", "Serbia"),
  ("SC", "248", "Seychelles"),
  ("SL", "232", "Sierra Leone"),
  ("SG", "65", "Singapore"),
  ("SK", "421", "Slovak Republic"),
  ("SI", "386", "Slovenia"),
  ("SB", "677", "Solomon Islands"),
  ("SO", "252", "Somalia"),
  ("ZA", "27", "South Africa"),
  ("ES", "34", "Spain"),
  ("LK", "94", "Sri Lanka"),
  ("SH", "290", "St. Helena"),
  ("KN", "1869", "St. Kitts"),
  ("SC", "1758", "St. Lucia"),
  ("SR", "597", "Suriname"),
  ("SD", "249", "Sudan"),
  ("SZ", "268", "Swaziland"),
  ("SE", "46", "Sweden"),
  ("CH", "41", "Switzerland"),
  ("TW", "886", "Taiwan"),
  ("TJ", "992", "Tajikistan"),
  ("TH", "66", "Thailand"),
  ("TG", "228", "Togo"),
  ("TO", "676", "Tonga"),
  ("TT", "1868", "Trinidad &amp; Tobago"),
  ("TN", "216", "Tunisia"),
  ("TR", "90", "Turkey"),
  ("TM", "993", "Turkmenistan"),
  ("TC", "1649", "Turks &amp; Caicos Islands"),
  ("TV", "688", "Tuvalu"),
  ("UG", "256", "Uganda"),
  ("UA", "380", "Ukraine"),
  ("AE", "971", "United Arab Emirates"),
  ("UY", "598", "Uruguay"),
  ("UZ", "998", "Uzbekistan"),
  ("VU", "678", "Vanuatu"),
  ("VA", "379", "Vatican City"),
  ("VE", "58", "Venezuela"),
  ("VN", "84", "Vietnam"),
  ("VG", "1", "Virgin Islands - British"),
  ("VI", "1", "Virgin Islands - US"),
  ("WF", "681", "Wallis &amp; Futuna"),
  ("YE", "969", "Yemen (North)"),
  ("YE", "967", "Yemen (South)"),
  ("ZM", "260", "Zambia"),
  ("ZW", "263", "Zimbabwe"),
